# Generated by Django 4.1 on 2024-12-03 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('sinopsis', models.TextField()),
                ('fecha_estreno', models.DateField()),
                ('duracion', models.IntegerField(help_text='Duración en minutos')),
                ('director', models.CharField(max_length=100)),
                ('image', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'película',
                'verbose_name_plural': 'películas',
            },
        ),
        migrations.CreateModel(
            name='PeliculaCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de asignación')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.categoria')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.pelicula')),
            ],
            options={
                'verbose_name': 'relación película-categoría',
                'verbose_name_plural': 'relaciones película-categoría',
                'unique_together': {('pelicula', 'categoria')},
            },
        ),
        migrations.AddField(
            model_name='pelicula',
            name='genero',
            field=models.ManyToManyField(through='database.PeliculaCategoria', to='database.categoria', verbose_name='Categorías'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Comentario')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='database.pelicula', verbose_name='Película')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'comentario',
                'verbose_name_plural': 'comentarios',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
